# Generated by Django 4.2.7 on 2023-12-05 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0010_batch_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Qualification', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Branch', models.ForeignKey(limit_choices_to={'isactive': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.branch', verbose_name='Branch')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'student',
                'ordering': ['-isactive'],
            },
        ),
    ]
