# Generated by Django 4.2.7 on 2023-12-07 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_students_ph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='ph',
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
