# Generated by Django 4.2.7 on 2023-12-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_general'),
    ]

    operations = [
        migrations.DeleteModel(
            name='General',
        ),
    ]
