# Generated by Django 4.2.7 on 2023-12-08 07:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_batch_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0006_delete_general'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['-isactive'], 'verbose_name_plural': 'students'},
        ),
        migrations.RemoveField(
            model_name='students',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='students',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.AddField(
            model_name='students',
            name='AlternativeEmail',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Alternativeaddress',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='CollegeName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Comments',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.district'),
        ),
        migrations.AddField(
            model_name='students',
            name='EnquirySources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.enquirysources'),
        ),
        migrations.AddField(
            model_name='students',
            name='NextFollowupDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='RegistrationNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='RollNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Student',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='students',
            name='StudentCallStatus',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Tostaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='students',
            name='Yearofpass',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.course'),
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photos/'),
        ),
        migrations.AddField(
            model_name='students',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.state'),
        ),
        migrations.AddField(
            model_name='students',
            name='whatsapp',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='Address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.qualification'),
        ),
        migrations.AddField(
            model_name='students',
            name='Dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
