# Generated by Django 4.2.7 on 2023-11-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'district'},
        ),
    ]
