# Generated by Django 4.2.7 on 2023-11-24 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0007_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('course', models.CharField(max_length=200, unique=True)),
                ('coursecode', models.CharField(max_length=200, null=True, unique=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trainers', models.ManyToManyField(blank=True, limit_choices_to={'issactive': True}, related_name='userTrainers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'course',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('batch', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('isclosed', models.BooleanField(default=False, verbose_name='closed')),
                ('Trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL, verbose_name='Trainer')),
                ('course', models.ForeignKey(limit_choices_to={'isactive': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.course', verbose_name='course')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batch',
            },
        ),
    ]
