# Generated by Django 4.2.7 on 2023-12-02 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0008_course_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='Branch',
            field=models.ForeignKey(limit_choices_to={'isactive': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='userTrainers', to=settings.AUTH_USER_MODEL),
        ),
    ]
