# Generated by Django 4.2.7 on 2023-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_batch_batch_batch_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
