# Generated by Django 4.2.7 on 2023-12-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_batch_end_time_batch_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
