# Generated by Django 4.2.7 on 2023-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_batch_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(),
        ),
    ]
